### ISSUE TITLE
Provide better error message for toc pointing to nonexistent MD

### ISSUE THREAD

**Issue by tsiq-karold** [twosigma/znai#76]
```
Exception in thread "main" java.lang.RuntimeException: error during parsing of <chapter-name/page-name>:/path/docs/mdoc/chapter-name/page-name.md doesn't exist
        at com.twosigma.documentation.website.WebSite.parseMarkupAndUpdateTocItem(WebSite.java:302)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
        at com.twosigma.documentation.website.WebSite.parseMarkups(WebSite.java:261)
        at com.twosigma.documentation.website.WebSite.generate(WebSite.java:134)
        at com.twosigma.documentation.website.WebSite$Configuration.deployTo(WebSite.java:570)
        at com.twosigma.documentation.cli.DocumentationCliApp.generateDocs(DocumentationCliApp.java:110)
        at com.twosigma.documentation.cli.DocumentationCliApp.start(DocumentationCliApp.java:65)
        at com.twosigma.documentation.cli.DocumentationCliApp.main(DocumentationCliApp.java:40)
Caused by: java.lang.RuntimeException: /path/docs/mdoc/chapter-name/page-name.md doesn't exist
        at com.twosigma.utils.FileUtils.fileTextContent(FileUtils.java:33)
        at com.twosigma.documentation.website.WebSite.parseMarkupAndUpdateTocItem(WebSite.java:285)
        ... 8 more
```

Pretty sure this was because I renamed the page and forgot to update toc.

**Comment by MykolaGolubyev** [comment]
Most recent build give this error. 
Could you please confirm 
```
Can't find "visuals/hello.md"

Tried following ResourceResolvers:
com.twosigma.znai.extensions.MultipleLocalLocationsResourceResolver resources not found:
  /Users/mykolagolubyev/work/znai/znai-docs/documentation/snippets/visuals/hello.md
  /Users/mykolagolubyev/work/znai/znai-docs/documentation/visuals/hello.md
  /Users/mykolagolubyev/work/znai/znai-console/src/main/java/visuals/hello.md
  /Users/mykolagolubyev/work/znai/znai-console/src/test/groovy/visuals/hello.md
  /Users/mykolagolubyev/work/znai/znai-jupyter/visuals/hello.md
  /Users/mykolagolubyev/work/znai/znai-testing-examples/visuals/hello.md
  /Users/mykolagolubyev/work/znai/znai-testing-examples/src/test/groovy/visuals/hello.md
  /Users/mykolagolubyev/work/znai/znai-testing-examples/src/test/java/visuals/hello.md
  /Users/mykolagolubyev/work/znai/znai-testing-examples/target/test-classes/visuals/hello.md
com.twosigma.znai.extensions.HttpBasedResourceResolver resources not found:
```

**Comment by MykolaGolubyev** [comment]
Actually I was just able to reproduce. Digging more.
